import { describe, expect, it } from 'vitest';
import type { Plate } from '../src/core/model';
import { applyEstimate, parseGcodeText, parseSliceInfo, parseSlicerDuration } from '../src/core/slicer';

describe('parseSlicerDuration', () => {
  it.each([
    ['7h 23m 12s', 443],
    ['1d 2h 3m 4s', 1563],
    ['45m 10s', 45],
    ['50s', 1],
  ])('%s', (text, min) => expect(parseSlicerDuration(text)).toBe(min));
});

describe('parseGcodeText', () => {
  it('reads PrusaSlicer comments, multi-material', () => {
    const gcode = [
      '; generated by PrusaSlicer 2.8.1+win64 on 2026-10-01 at 10:00:00 UTC',
      'G1 X10 Y10',
      '; filament used [mm] = 63021.11, 1450.20',
      '; filament used [g] = 187.95, 4.32',
      '; total filament used [g] = 192.27',
      '; estimated printing time (normal mode) = 7h 23m 12s',
      '; filament_type = PLA;PETG',
    ].join('\n');
    expect(parseGcodeText(gcode)).toEqual({ slicer: 'PrusaSlicer', printTimeMin: 443, filamentG: [187.95, 4.32], filamentM: [], filamentTypes: ['PLA', 'PETG'] });
  });

  it('reads Prusa binary G-code metadata (key=value without comment marker)', () => {
    const meta = 'printer_model=COREONE\nfilament used [g]=25.10\nestimated printing time (normal mode)=1h 5m 30s\nfilament_type=PLA';
    expect(parseGcodeText(`GCDE\u0001\u0000${meta}\u0000\u0007binary`)).toMatchObject({ printTimeMin: 66, filamentG: [25.1], filamentTypes: ['PLA'] });
  });

  it('reads Bambu Studio / OrcaSlicer headers, preferring the total estimated time', () => {
    const gcode = [
      '; HEADER_BLOCK_START',
      '; BambuStudio 01.09.00.70',
      '; model printing time: 1h 2m 10s; total estimated time: 1h 10m 3s',
      '; total filament weight [g] : 20.50',
      '; HEADER_BLOCK_END',
    ].join('\n');
    expect(parseGcodeText(gcode)).toEqual({ slicer: 'BambuStudio', printTimeMin: 70, filamentG: [20.5], filamentM: [], filamentTypes: [] });
  });

  it('reads Cura time and filament length', () => {
    expect(parseGcodeText(';FLAVOR:Marlin\n;TIME:26592\n;Filament used: 5.23456m\n')).toEqual({
      slicer: 'Cura', printTimeMin: 443, filamentG: [], filamentM: [5.23456], filamentTypes: [],
    });
  });

  it('returns null for G-code without estimates', () => {
    expect(parseGcodeText('G28\nG1 X0 Y0\n')).toBeNull();
  });
});

describe('parseSliceInfo', () => {
  it('reads one estimate per plate from a Bambu/Orca 3MF', () => {
    const xml = `<config><plate>
      <metadata key="index" value="1"/><metadata key="prediction" value="3725"/><metadata key="weight" value="31.20"/>
      <filament id="1" type="PLA" color="#000000" used_m="9.50" used_g="28.40"/>
      <filament id="2" type="PETG" color="#FFFFFF" used_m="0.90" used_g="2.80"/>
    </plate><plate><metadata key="prediction" value="600"/><filament id="1" type="PLA" used_g="5"/></plate></config>`;
    expect(parseSliceInfo(xml)).toEqual([
      { slicer: 'Bambu/Orca 3MF', printTimeMin: 62, filamentG: [28.4, 2.8], filamentM: [], filamentTypes: ['PLA', 'PETG'] },
      { slicer: 'Bambu/Orca 3MF', printTimeMin: 10, filamentG: [5], filamentM: [], filamentTypes: ['PLA'] },
    ]);
  });
});

describe('applyEstimate', () => {
  const plate = (): Plate => ({ id: 'p', name: 'Plate 1', printerId: 'x', printTimeMin: 60, runs: 1, filaments: [{ filamentId: 'black', weightG: 0 }], filamentChanges: 20 });

  it('fills time and grams in slot order, adds rows, clears purge for multi-material', () => {
    const p = plate();
    applyEstimate(p, { slicer: 'x', printTimeMin: 443, filamentG: [187.954, 4.32], filamentM: [], filamentTypes: [] }, () => 3, 'Bins');
    expect(p).toMatchObject({ name: 'Bins', printTimeMin: 443, purgeG: 0, filaments: [{ filamentId: 'black', weightG: 187.95 }, { filamentId: '', weightG: 4.32 }] });
    expect(p.filamentChanges).toBeUndefined();
  });

  it('converts Cura lengths and keeps custom plate names', () => {
    const p = { ...plate(), name: 'Gridfinity base' };
    applyEstimate(p, { slicer: 'Cura', printTimeMin: 100, filamentG: [], filamentM: [10], filamentTypes: [] }, () => 2.98, 'file');
    expect(p.filaments[0]!.weightG).toBeCloseTo(29.8, 6);
    expect(p.name).toBe('Gridfinity base');
    expect(p.filamentChanges).toBe(20);
  });
});
