import type { Plate } from './model';

/**
 * Reads print time and filament usage from slicer output (QC-8). Works on the
 * text of the G-code comments; callers pass the head and tail of large files.
 * Supported: PrusaSlicer / OrcaSlicer / Bambu Studio / SuperSlicer (also the
 * metadata of Prusa binary G-code and Bambu/Orca 3MF slice info), Cura.
 */

export interface SlicerEstimate {
  slicer: string;
  printTimeMin: number | null;
  /** Grams per extruder/filament slot, in slot order. */
  filamentG: number[];
  /** Filament length per slot in meters, when grams are missing (Cura). */
  filamentM: number[];
  filamentTypes: string[];
}

/** "7h 23m 12s", "1d 2h 3m", "45m 10s" → minutes. */
export function parseSlicerDuration(text: string): number | null {
  const re = /(\d+(?:\.\d+)?)\s*([dhms])/g;
  let seconds = 0;
  let found = false;
  for (const m of text.matchAll(re)) {
    found = true;
    seconds += Number(m[1]) * { d: 86400, h: 3600, m: 60, s: 1 }[m[2] as 'd' | 'h' | 'm' | 's'];
  }
  return found ? Math.round(seconds / 60) : null;
}

const numbers = (text: string) => text.split(/[,;]/).map((x) => Number.parseFloat(x)).filter((x) => Number.isFinite(x));

export function parseGcodeText(text: string): SlicerEstimate | null {
  // Values end at line breaks or, in binary G-code, at any other control byte.
  const value = (pattern: RegExp) => pattern.exec(text)?.[1]?.trim();

  // PrusaSlicer family: "; estimated printing time (normal mode) = 7h 23m 12s", "; filament used [g] = 12.3, 4.5"
  // Bambu/Orca header:  "; model printing time: 1h 2m; total estimated time: 1h 10m", "; total filament weight [g] : 20.5"
  // Prusa binary G-code metadata uses the same keys without "; ".
  const total = value(/total estimated time:\s*([^;\x00-\x1f]+)/i);
  const prusaTime = value(/estimated printing time \(normal mode\)\s*=\s*([^\x00-\x1f]+)/i);
  const grams = value(/^[;\s]*filament used \[g\]\s*=\s*([^\x00-\x1f]+)/im);
  const totalWeight = value(/total filament (?:weight|used) \[g\]\s*[:=]\s*([^\x00-\x1f]+)/i);
  const types = value(/^[;\s]*filament_type\s*=\s*([^\x00-\x1f]+)/im);
  if (prusaTime || total || grams || totalWeight) {
    const slicer = value(/generated by (\w+)/i) ?? value(/^;\s*(BambuStudio|OrcaSlicer)/im) ?? 'PrusaSlicer-compatible';
    const perSlot = grams ? numbers(grams) : [];
    return {
      slicer,
      printTimeMin: parseSlicerDuration(total ?? prusaTime ?? ''),
      filamentG: perSlot.length > 0 ? perSlot : totalWeight ? numbers(totalWeight).slice(0, 1) : [],
      filamentM: [],
      filamentTypes: types ? types.split(/[;,]/).map((t) => t.trim()).filter(Boolean) : [],
    };
  }

  // Cura: ";TIME:26592" (seconds), ";Filament used: 5.23456m, 1.2m"
  const curaTime = value(/^;TIME:(\d+)/m);
  const curaUsed = value(/^;Filament used:\s*([^\n]+)/m);
  if (curaTime || curaUsed) {
    return {
      slicer: 'Cura',
      printTimeMin: curaTime ? Math.round(Number(curaTime) / 60) : null,
      filamentG: [],
      filamentM: curaUsed ? numbers(curaUsed.replace(/m/g, '')) : [],
      filamentTypes: [],
    };
  }
  return null;
}

/** Bambu Studio / OrcaSlicer 3MF: Metadata/slice_info.config (one <plate> per sliced plate). */
export function parseSliceInfo(xml: string): SlicerEstimate[] {
  const plates = [...xml.matchAll(/<plate>([\s\S]*?)<\/plate>/g)].map((m) => m[1]!);
  return plates.map((p) => {
    const meta = (key: string) => new RegExp(`<metadata key="${key}" value="([^"]*)"`).exec(p)?.[1];
    const filaments = [...p.matchAll(/<filament ([^>]*)\/>/g)].map((m) => m[1]!);
    const attr = (f: string, key: string) => new RegExp(`${key}="([^"]*)"`).exec(f)?.[1];
    const seconds = Number(meta('prediction'));
    return {
      slicer: 'Bambu/Orca 3MF',
      printTimeMin: Number.isFinite(seconds) && seconds > 0 ? Math.round(seconds / 60) : null,
      filamentG: filaments.map((f) => Number(attr(f, 'used_g'))).filter(Number.isFinite),
      filamentM: [],
      filamentTypes: filaments.map((f) => attr(f, 'type') ?? '').filter(Boolean),
    };
  });
}

/**
 * Applies an estimate to a plate: print time, and grams per filament row in slot
 * order (rows are added when the file has more slots). Slicer grams already
 * include wipe tower and purge, so the plate's own purge settings are cleared.
 * Lengths (Cura) are converted with `gramsPerMeter(slot)`.
 */
export function applyEstimate(
  plate: Plate,
  est: SlicerEstimate,
  gramsPerMeter: (slot: number) => number,
  name?: string,
): void {
  if (est.printTimeMin !== null) plate.printTimeMin = est.printTimeMin;
  const grams = est.filamentG.length > 0 ? est.filamentG : est.filamentM.map((m, i) => m * gramsPerMeter(i));
  grams.forEach((g, i) => {
    const weightG = Math.round(g * 100) / 100;
    if (plate.filaments[i]) plate.filaments[i]!.weightG = weightG;
    else plate.filaments.push({ filamentId: '', weightG });
  });
  if (grams.length > 1) {
    plate.purgeG = 0;
    delete plate.filamentChanges;
  }
  if (name && /^Plate \d+$/.test(plate.name)) plate.name = name;
}
